# Generated by Django 4.1.6 on 2023-02-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadingsAndDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headingOne', models.CharField(max_length=1000)),
                ('headingTwo', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2500)),
            ],
        ),
    ]
