# Generated by Django 4.1.6 on 2023-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.ImageField(upload_to='../Cafe/static/img')),
            ],
        ),
    ]
