# Generated by Django 4.1.6 on 2023-02-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0003_alter_landingpagebackgroundimage_backgroundimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandingPageBackgroundImage',
            new_name='LandingPageBackgroundImg',
        ),
    ]
