# Generated by Django 4.1.6 on 2023-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0004_rename_landingpagebackgroundimage_landingpagebackgroundimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.ImageField(upload_to='Cafe/static/img')),
            ],
        ),
        migrations.DeleteModel(
            name='LandingPageBackgroundImg',
        ),
    ]
