# Generated by Django 4.1.6 on 2023-02-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0005_landingpagebackground_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='LandingPageBackground',
        ),
    ]
