# Generated by Django 4.1.6 on 2023-02-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0006_landingbackground_delete_landingpagebackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotatingImageInLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('backgroundImage', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='LandingBackground',
        ),
    ]
