# Generated by Django 4.1.6 on 2023-02-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0009_ladningpageservices_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageAboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.CharField(max_length=20)),
                ('welcome_text', models.CharField(max_length=20)),
                ('restaurant_name', models.CharField(max_length=20)),
                ('img1', models.ImageField(upload_to='img/%y')),
                ('img2', models.ImageField(upload_to='img/%y')),
                ('img3', models.ImageField(upload_to='img/%y')),
                ('img4', models.ImageField(upload_to='img/%y')),
                ('description_1', models.CharField(max_length=1000)),
                ('description_2', models.CharField(max_length=1000)),
                ('counter1_num', models.IntegerField()),
                ('counter1_text1', models.CharField(max_length=20)),
                ('counter1_text2', models.CharField(max_length=20)),
                ('counter2_num', models.IntegerField()),
                ('counter2_text1', models.CharField(max_length=20)),
                ('counter2_text2', models.CharField(max_length=20)),
                ('button_text', models.CharField(max_length=20)),
                ('button_link', models.CharField(max_length=2500)),
            ],
        ),
    ]
