# Generated by Django 4.1.6 on 2023-02-07 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0015_landingpagetestimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagetestimonial',
            name='testimonial_description',
        ),
        migrations.RemoveField(
            model_name='landingpagetestimonial',
            name='testimonial_text',
        ),
    ]
