# Generated by Django 4.1.6 on 2023-02-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0018_footerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageMenuBreakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_breakfast_item_name', models.CharField(max_length=150)),
                ('menu_breakfast_item_description', models.CharField(max_length=255)),
                ('menu_breakfast_item_price', models.IntegerField()),
                ('menu_breakfast_item_img', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageMenuDinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_breakfast_item_name', models.CharField(max_length=150)),
                ('menu_breakfast_item_description', models.CharField(max_length=255)),
                ('menu_breakfast_item_price', models.IntegerField()),
                ('menu_breakfast_item_img', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageMenuHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_text', models.CharField(max_length=20)),
                ('menu_heading', models.CharField(max_length=100)),
                ('menu_breakfast_description', models.CharField(max_length=20)),
                ('menu_breakfast_text', models.CharField(max_length=20)),
                ('menu_lunch_description', models.CharField(max_length=20)),
                ('menu_lunch_text', models.CharField(max_length=20)),
                ('menu_dinner_description', models.CharField(max_length=20)),
                ('menu_dinner_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageMenuLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_breakfast_item_name', models.CharField(max_length=150)),
                ('menu_breakfast_item_description', models.CharField(max_length=255)),
                ('menu_breakfast_item_price', models.IntegerField()),
                ('menu_breakfast_item_img', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='LandingPageMenuSection',
        ),
    ]
