# Generated by Django 4.1.6 on 2023-02-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0020_threedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image_heading', models.CharField(max_length=50)),
                ('gallery_image_description', models.CharField(max_length=255)),
                ('gallery_image', models.ImageField(upload_to='img/%y')),
            ],
        ),
    ]
